services:
  backend:
    image: docker.ub.gu.se/libris-xl:${GIT_REVISION}
    restart: always
    environment:
      - RAILS_ENVIRONMENT=${ENVIRONMENT}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - LIBRIS_CLIENT_ID=${LIBRIS_CLIENT_ID}
      - LIBRIS_CLIENT_SECRET=${LIBRIS_CLIENT_SECRET}
      - LIBRIS_TOKEN_URL=${LIBRIS_TOKEN_URL}
      - LIBRIS_API_BASE_URL=${LIBRIS_API_BASE_URL}
      - LIBRIS_RESOURCE_BASE_URL=${LIBRIS_RESOURCE_BASE_URL}
      - DFLOW_API_KEY=${DFLOW_API_KEY}
      - TYPE=${TYPE}
      - PLACE=${PLACE}
      - AGENT=${AGENT}
      - PUBLICNOTE=${PUBLICNOTE}
      - REMARK=${REMARK}
      - PUBLICNOTE_HOLDING=${PUBLICNOTE_HOLDING}
      - REMARK_HOLDING=${REMARK_HOLDING}
      - BIBLIOGRAPHIC_CODE=${BIBLIOGRAPHIC_CODE}
      - ADDITIONAL_BIBLIOGRAPHIC_CODE=${ADDITIONAL_BIBLIOGRAPHIC_CODE}
      - SIGEL=${SIGEL}
    ports:
      - ${EXPOSED_PORT}:3000